### ISSUE TITLE
Exception after running Serializers.Register()

### ISSUE THREAD

**Issue by afshawnlotfi** [tkellogg/MongoDB.FSharp#14]
Exception has occurred: CLR/System.TypeLoadException
An exception of type 'System.TypeLoadException' occurred in myapp.dll but was not handled in user code: 'Could not load type 'MongoDB.Bson.Serialization.Serializers.BsonBaseSerializer' from assembly 'MongoDB.Bson, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null'.'

Specs:
<TargetFramework>netcoreapp2.2</TargetFramework>

**Comment by starychfojtu** [comment]
Same here with version 2.7.0.0

**Comment by rodsfreitas** [comment]
Any update here?

**Comment by afshawnlotfi** [comment]
A long time ago when I asked this question I ended up just forking another package that does the same thing and making it compatible with the newest framework and even got NUnit support. https://github.com/afshawnlotfi/FSharp.MongoDB
